ia:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' 
      server: DESKTOP-F1N1BGK\MSSQLSERVER01
      port: 1433
      database: InternalApp
      schema: dbt_bobocg
      windows_login: True
      trust_cert: True
      